# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bt_MTI4iBv5QLfzR9cei1DymtQHOZsa-
"""

# ============================================================
# SEDLAC Parser — Colab
# Arquivos: 2024_Act1_poverty_LAC.xlsx
#            2025_Act1_inequality_LAC.xlsx
# ============================================================

# =============================================================================
# 0. PREPARATIVOS
# =============================================================================

# --- Importando pacotes e bibliotecas
import pandas as pd
import re
from openpyxl     import load_workbook
from google.colab import files

# --- Subindo todos os arquivos necessários de uma vez
uploaded = files.upload()

# =============================================================================
# 1. PARAMETRIZAÇÃO
# =============================================================================

# --- Dicionário de países
LAC_COUNTRIES = {
    'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia',
    'Costa Rica', 'Dominican Republic', 'Ecuador', 'El Salvador',
    'Guatemala', 'Guyana', 'Haiti', 'Honduras', 'Jamaica',
    'Mexico', 'Nicaragua', 'Panama', 'Paraguay', 'Peru',
    'Suriname', 'Uruguay', 'Venezuela', 'Bahamas', 'Belize'
}

# --- Funções de tratamento
def is_data_row(row):
    return (parse_year(row[0]) is not None
            and any(isinstance(v, (int, float)) for v in row[1:5]))

def is_label_row(row):
    return (isinstance(row[0], str)
            and not isinstance(row[1], (int, float))
            and not isinstance(row[2], (int, float)))

# --- Funções de parsing
def parse_year(val):
    '''Extrai ano inteiro de int, float ou strings como "2003-II".'''
    if isinstance(val, (int, float)) and not pd.isna(val):
        return int(val)
    if isinstance(val, str):
        m = re.match(r'^(\d{4})', val.strip())
        if m:
            return int(m.group(1))
    return None

def parse_sheet(filepath, sheetname, col_map):
    '''
    col_map: dict {nome_coluna: indice_coluna}
    Retorna DataFrame longo com: country, region, year, + colunas de col_map
    '''
    wb = load_workbook(filepath, read_only=True)
    ws = wb[sheetname]

    records = []
    current_country = None
    current_region = None

    for row in ws.iter_rows(values_only=True):
        if is_label_row(row):
            name = str(row[0]).strip()
            if name in LAC_COUNTRIES:
                current_country = name
                current_region = None
            elif current_country and row[1] is None:
                current_region = name  # região subnacional
        elif is_data_row(row) and current_country:
            year = parse_year(row[0])
            rec = {
                'country': current_country,
                'region': current_region,
                'year': year
            }
            for col_name, col_idx in col_map.items():
                val = row[col_idx] if len(row) > col_idx else None
                rec[col_name] = val if isinstance(val, (int, float)) else None
            records.append(rec)

    wb.close()
    return pd.DataFrame(records)

def parse_region_sheet(filepath, sheetname, poverty_line):
    '''Extrai dados a nível regional para cada país'''
    wb = load_workbook(filepath, read_only=True)
    ws = wb[sheetname]
    records = []
    current_country = None
    current_subsample = None
    region_headers = []

    for row in ws.iter_rows(values_only=True):
        col0 = row[0]

        if isinstance(col0, str) and ' '.join(col0.split()) in LAC_COUNTRIES:
            current_country = ' '.join(col0.split())
            region_headers = []
            current_subsample = None

        elif current_country and col0 is None and isinstance(row[1], str):
            # linha de cabeçalho das regiões
            region_headers = [v for v in row[1:] if v is not None]

        elif (current_country and isinstance(col0, str)
              and col0.strip() not in LAC_COUNTRIES
              and all(v is None for v in row[1:5])):
            current_subsample = col0.strip()

        elif current_country and region_headers and is_data_row(row):
            year = parse_year(row[0])
            for i, region_name in enumerate(region_headers):
                val = row[i + 1] if len(row) > i + 1 else None
                if isinstance(val, (int, float)):
                    records.append({
                        'country': current_country,
                        'subsample': current_subsample,
                        'region': region_name,
                        'year': year,
                        'headcount': val,
                        'poverty_line': poverty_line
                    })

    wb.close()
    return pd.DataFrame(records)

# =============================================================================
# 2A. BASES SOBRE POBREZA
# =============================================================================

# --- Tabelas com dados de pobreza monetária (nacional, urbano/rural)
pov_215 = parse_sheet(
    '2024_Act1_poverty_LAC.xlsx', 'poverty USD2.15',
    {'headcount_national': 1, 'headcount_urban': 5, 'headcount_rural': 9}
)
pov_215['poverty_line'] = 'USD2.15'

pov_365 = parse_sheet(
    '2024_Act1_poverty_LAC.xlsx', 'poverty USD3.65',
    {'headcount_national': 1, 'headcount_urban': 5, 'headcount_rural': 9}
)
pov_365['poverty_line'] = 'USD3.65'

pov_685 = parse_sheet(
    '2024_Act1_poverty_LAC.xlsx', 'poverty USD6.85',
    {'headcount_national': 1, 'headcount_urban': 5, 'headcount_rural': 9}
)
pov_685['poverty_line'] = 'USD6.85'

poverty_main = pd.concat([pov_215, pov_365, pov_685], ignore_index=True)

# --- Tabelas com dados de pobreza monetária (regional)
reg_215 = parse_region_sheet('2024_Act1_poverty_LAC.xlsx', 'region_2.15', 'USD2.15')
reg_365 = parse_region_sheet('2024_Act1_poverty_LAC.xlsx', 'region_3.65', 'USD3.65')
reg_685 = parse_region_sheet('2024_Act1_poverty_LAC.xlsx', 'region_6.85', 'USD6.85')

poverty_regional = pd.concat([reg_215, reg_365, reg_685], ignore_index=True)

# --- Tabela com dados sobre NBI (nacional, apenas urbano)
nbi1 = parse_sheet(
    '2024_Act1_poverty_LAC.xlsx', 'NBI1',
    {'headcount_urban': 1}
)
nbi1['indicator'] = 'NBI1'

# --- Exportação de objetos
poverty_main.to_csv('sedlac_poverty_main.csv', index=False)
print(f'poverty_main:     {len(poverty_main)} linhas')

poverty_regional.to_csv('sedlac_poverty_regional.csv', index=False)
print(f'poverty_regional: {len(poverty_regional)} linhas')

nbi1.to_csv('sedlac_nbi1.csv', index=False)
print(f'nbi1:             {len(nbi1)} linhas')

# =============================================================================
# 2B. BASES SOBRE DESIGUALDADE
# =============================================================================

# --- Tabelas com dados do Índice de Gini (nacional, urbano/rural)
gini1 = parse_sheet(
    '2025_Act1_inequality_LAC.xlsx', 'gini1',
    {'gini_pci': 1}
)

gini2 = parse_sheet(
    '2025_Act1_inequality_LAC.xlsx', 'gini2',
    {'gini_pci_urban': 1, 'gini_pci_rural': 2}
)

# --- Tabelas com dados do Índice de Wolfson (nacional)
polarization = parse_sheet(
    '2025_Act1_inequality_LAC.xlsx', 'polarization',
    {'wolfson': 1}
)

# --- Tabelas com Indicadores de Desigualdade (Theil, CV, Atkinson)
indices_pci = parse_sheet(
    '2025_Act1_inequality_LAC.xlsx', 'indices pci',
    {
        'gini':   1,
        'theil':  2,
        'cv':     3,
        'a1':     5,
        'a2':     6,
        'e0':     7
    }
)

# --- Tabelas com participação por decis
deciles_pci = parse_sheet(
    '2025_Act1_inequality_LAC.xlsx', 'deciles pci',
    {
        'd1': 1, 'd2': 2, 'd3': 3, 'd4':  4,  'd5':  5,
        'd6': 6, 'd7': 7, 'd8': 8, 'd9':  9,  'd10': 10,
        'ratio_10_1': 12
    }
)

# --- Exportação de objetos
gini1.to_csv('sedlac_gini1.csv', index=False)
print(f'gini1:        {len(gini1)} linhas')

gini2.to_csv('sedlac_gini2.csv', index=False)
print(f'gini2:        {len(gini2)} linhas')

polarization.to_csv('sedlac_polarization.csv', index=False)
print(f'polarization: {len(polarization)} linhas')

indices_pci.to_csv('sedlac_indices_pci.csv', index=False)
print(f'indices_pci:  {len(indices_pci)} linhas')

deciles_pci.to_csv('sedlac_deciles_pci.csv', index=False)
print(f'deciles_pci:  {len(deciles_pci)} linhas')

# =============================================================================
# 3. ARQUIVOS PARA DASHBOARD
# =============================================================================

frames = []

# --- OBJETOS NECESSÁRIOS

# poverty_main: headcount nacional/urbano/rural × 3 linhas de pobreza
melted_pov = poverty_main.melt(
    id_vars=['country', 'region', 'year', 'poverty_line'],
    value_vars=['headcount_national', 'headcount_urban', 'headcount_rural'],
    var_name='measure',
    value_name='value'
)
melted_pov['indicator'] = melted_pov['measure'] + '_' + melted_pov['poverty_line']
melted_pov = melted_pov[['country', 'region', 'year', 'indicator', 'value']]
frames.append(melted_pov)

# nbi1: pobreza multidimensional urbana
nbi_long = nbi1[['country', 'region', 'year', 'headcount_urban']].copy()
nbi_long['indicator'] = 'nbi1_headcount_urban'
nbi_long = nbi_long.rename(columns={'headcount_urban': 'value'})
frames.append(nbi_long[['country', 'region', 'year', 'indicator', 'value']])

# gini2: Gini per capita urbano e rural
melted_gini2 = gini2.melt(
    id_vars=['country', 'region', 'year'],
    value_vars=['gini_pci_urban', 'gini_pci_rural'],
    var_name='indicator',
    value_name='value'
)
frames.append(melted_gini2)

# polarization: Wolfson
pol_long = polarization[['country', 'region', 'year', 'wolfson']].copy()
pol_long['indicator'] = 'wolfson'
pol_long = pol_long.rename(columns={'wolfson': 'value'})
frames.append(pol_long[['country', 'region', 'year', 'indicator', 'value']])

# indices_pci: gini, theil, cv, a1, a2, e0
melted_indices = indices_pci.melt(
    id_vars=['country', 'region', 'year'],
    value_vars=['gini', 'theil', 'cv', 'a1', 'a2', 'e0'],
    var_name='indicator',
    value_name='value'
)
frames.append(melted_indices)

# --- ARQUIVO 1: sedlac_indicators.csv
indicators = (
    pd.concat(frames, ignore_index=True)
    .dropna(subset=['value'])
    .sort_values(['country', 'region', 'year', 'indicator'])
    .reset_index(drop=True)
)
indicators.to_csv('sedlac_indicators.csv', index=False, decimal=',', sep=';')

# --- ARQUIVO 2: sedlac_deciles.csv
decile_cols = ['d1','d2','d3','d4','d5','d6','d7','d8','d9','d10','ratio_10_1']
deciles_long = (
    deciles_pci
    .melt(
        id_vars=['country', 'region', 'year'],
        value_vars=decile_cols,
        var_name='decile',
        value_name='share'
    )
    .dropna(subset=['share'])
    .sort_values(['country', 'region', 'year', 'decile'])
    .reset_index(drop=True)
)
deciles_long.to_csv('sedlac_deciles.csv', index=False, decimal=',', sep=';')

# --- ARQUIVO 3: sedlac_regional.csv
poverty_regional.to_csv('sedlac_regional.csv', index=False, decimal=',', sep=';')

# --- AVALIANDO RESULTADOS
print(f'indicators:  {len(indicators):,} linhas')
print(f'indicadores: {sorted(indicators["indicator"].unique())}')
print()
print(f'deciles:     {len(deciles_long):,} linhas')
print()
print(f'regional:    {len(poverty_regional):,} linhas')

# --- Download ---
files.download('sedlac_indicators.csv')
files.download('sedlac_deciles.csv')
files.download('sedlac_regional.csv')